run:
  deadline: 5m
  tests: false
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - maintidx
    - ireturn
    - contextcheck
    - lll
    - goerr113
    - nestif
    - funlen
    - gci
    - gofumpt
    - goimports
    - dupl
    - godox
    - gocognit
    - gocyclo
    - cyclop
    - gomnd
    - forcetypeassert
    - tagliatelle
    - revive
    - interfacer
    - scopelint
    - golint
    - maligned
    - exhaustivestruct
    - gochecknoglobals
    - gocritic
    - godot
    - stylecheck
    - govet
    - staticcheck
    - ineffassign
    - wastedassign
    - varnamelen
